Throw Exception
===============

The Throw Exception function interrupts a process by throwing an exception. This exception will either be caught by the nearest Try Catch function that the Throw Exception function is in scope of or, if no Try Catch functions exist in the current scope, then the entire process will fail.

Properties
----------

-  #### Message

    The message that the exception should carry when thrown.


